name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Install enumer and generate enums
        run: |
          go get github.com/dmarkham/enumer
          go install github.com/dmarkham/enumer
          go generate ./...
      - name: build
        run: docker build -t metamemelord/portfolio .
